---

- name: Download the cloudwatch logs agent
  get_url:
    url: https://s3.amazonaws.com/aws-cloudwatch/downloads/latest/awslogs-agent-setup.py
    dest: /tmp/awslogs-agent-setup.py
    mode: 0750

- name: Ensure OS Distro is in /etc/issue
  lineinfile:
    path: /etc/issue
    create: yes
    insertbefore: BOF
    regexp: "^{{ansible_distribution}}"
    line: "{{ansible_lsb.description | default(ansible_distribution)}}"
    state: present

- name: Create /tmp/awslogs.conf
  copy:
    src: awslogs.conf
    dest: /tmp/awslogs.conf
    owner: root
    group: root
    mode: 0600

- name: Run awslogs agent setup
  command: "{{awslogs_install_command}}"
  ignore_errors: yes
  register: awslogs_install

# CIS versions of Ubuntu fail due to a permissions issue
# https://forums.aws.amazon.com/thread.jspa?threadID=232057
- block:
    - name: Make /var/awslogs/bin/aws executable
      file: path=/var/awslogs/bin/aws mode=0750

    - name: Re-run awslogs agent setup
      command: "{{awslogs_install_command}}"
  when: awslogs_install is failed
